# Generated by Django 4.1.7 on 2023-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
