# Generated by Django 4.1.7 on 2023-04-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_legislation_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='details',
            field=models.TextField(),
        ),
    ]
