# Generated by Django 4.1.7 on 2023-03-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatdata', '0002_legislation_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionanswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('keywords', models.TextField()),
                ('keyphrase', models.TextField()),
            ],
        ),
    ]
