# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

on: 

  push: 

    branches: [ main ] 

    paths: 

    - 'bot.py' 

    - 'lint.py' 
 

jobs: 

  build: 

    runs-on: ubuntu-latest 

    steps: 

    - uses: actions/checkout@v2 

    - name: Set up Python 3.8 

      uses: actions/setup-python@v2 

      with: 

        python-version: 3.8 

    - name: Install dependencies 

      run: | 

        python -m pip install --upgrade pip 

        pip install pylint 

    - name: Lint with pylint 

      run: | 

        python lint.py 

    - name: Test with pytest

        run: |

          pip install pytest

          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
